// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sparkplug.proto

package sparkplug

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payload struct {
	Timestamp                    *uint64           `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Metrics                      []*Payload_Metric `protobuf:"bytes,2,rep,name=metrics" json:"metrics,omitempty"`
	Seq                          *uint64           `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
	Uuid                         *string           `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	Body                         []byte            `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}          `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0}
}

var extRange_Payload = []proto.ExtensionRange{
	{Start: 6, End: 536870911},
}

func (*Payload) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Payload) GetMetrics() []*Payload_Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *Payload) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *Payload) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *Payload) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Payload_Template struct {
	Version                      *string                       `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	Metrics                      []*Payload_Metric             `protobuf:"bytes,2,rep,name=metrics" json:"metrics,omitempty"`
	Parameters                   []*Payload_Template_Parameter `protobuf:"bytes,3,rep,name=parameters" json:"parameters,omitempty"`
	TemplateRef                  *string                       `protobuf:"bytes,4,opt,name=template_ref,json=templateRef" json:"template_ref,omitempty"`
	IsDefinition                 *bool                         `protobuf:"varint,5,opt,name=is_definition,json=isDefinition" json:"is_definition,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                      `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_Template) Reset()         { *m = Payload_Template{} }
func (m *Payload_Template) String() string { return proto.CompactTextString(m) }
func (*Payload_Template) ProtoMessage()    {}
func (*Payload_Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 0}
}

var extRange_Payload_Template = []proto.ExtensionRange{
	{Start: 6, End: 536870911},
}

func (*Payload_Template) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_Template
}

func (m *Payload_Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Template.Unmarshal(m, b)
}
func (m *Payload_Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Template.Marshal(b, m, deterministic)
}
func (m *Payload_Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Template.Merge(m, src)
}
func (m *Payload_Template) XXX_Size() int {
	return xxx_messageInfo_Payload_Template.Size(m)
}
func (m *Payload_Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Template proto.InternalMessageInfo

func (m *Payload_Template) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Payload_Template) GetMetrics() []*Payload_Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *Payload_Template) GetParameters() []*Payload_Template_Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Payload_Template) GetTemplateRef() string {
	if m != nil && m.TemplateRef != nil {
		return *m.TemplateRef
	}
	return ""
}

func (m *Payload_Template) GetIsDefinition() bool {
	if m != nil && m.IsDefinition != nil {
		return *m.IsDefinition
	}
	return false
}

type Payload_Template_Parameter struct {
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type *uint32 `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Payload_Template_Parameter_IntValue
	//	*Payload_Template_Parameter_LongValue
	//	*Payload_Template_Parameter_FloatValue
	//	*Payload_Template_Parameter_DoubleValue
	//	*Payload_Template_Parameter_BooleanValue
	//	*Payload_Template_Parameter_StringValue
	//	*Payload_Template_Parameter_ExtensionValue
	Value                isPayload_Template_Parameter_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *Payload_Template_Parameter) Reset()         { *m = Payload_Template_Parameter{} }
func (m *Payload_Template_Parameter) String() string { return proto.CompactTextString(m) }
func (*Payload_Template_Parameter) ProtoMessage()    {}
func (*Payload_Template_Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 0, 0}
}

func (m *Payload_Template_Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Template_Parameter.Unmarshal(m, b)
}
func (m *Payload_Template_Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Template_Parameter.Marshal(b, m, deterministic)
}
func (m *Payload_Template_Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Template_Parameter.Merge(m, src)
}
func (m *Payload_Template_Parameter) XXX_Size() int {
	return xxx_messageInfo_Payload_Template_Parameter.Size(m)
}
func (m *Payload_Template_Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Template_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Template_Parameter proto.InternalMessageInfo

func (m *Payload_Template_Parameter) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Payload_Template_Parameter) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

type isPayload_Template_Parameter_Value interface {
	isPayload_Template_Parameter_Value()
}

type Payload_Template_Parameter_IntValue struct {
	IntValue uint32 `protobuf:"varint,3,opt,name=int_value,json=intValue,oneof"`
}

type Payload_Template_Parameter_LongValue struct {
	LongValue uint64 `protobuf:"varint,4,opt,name=long_value,json=longValue,oneof"`
}

type Payload_Template_Parameter_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,5,opt,name=float_value,json=floatValue,oneof"`
}

type Payload_Template_Parameter_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue,oneof"`
}

type Payload_Template_Parameter_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,7,opt,name=boolean_value,json=booleanValue,oneof"`
}

type Payload_Template_Parameter_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,oneof"`
}

type Payload_Template_Parameter_ExtensionValue struct {
	ExtensionValue *Payload_Template_Parameter_ParameterValueExtension `protobuf:"bytes,9,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_Template_Parameter_IntValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_LongValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_FloatValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_DoubleValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_BooleanValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_StringValue) isPayload_Template_Parameter_Value() {}

func (*Payload_Template_Parameter_ExtensionValue) isPayload_Template_Parameter_Value() {}

func (m *Payload_Template_Parameter) GetValue() isPayload_Template_Parameter_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Payload_Template_Parameter) GetIntValue() uint32 {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Payload_Template_Parameter) GetLongValue() uint64 {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Payload_Template_Parameter) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Payload_Template_Parameter) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Payload_Template_Parameter) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *Payload_Template_Parameter) GetStringValue() string {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Payload_Template_Parameter) GetExtensionValue() *Payload_Template_Parameter_ParameterValueExtension {
	if x, ok := m.GetValue().(*Payload_Template_Parameter_ExtensionValue); ok {
		return x.ExtensionValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Payload_Template_Parameter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Payload_Template_Parameter_IntValue)(nil),
		(*Payload_Template_Parameter_LongValue)(nil),
		(*Payload_Template_Parameter_FloatValue)(nil),
		(*Payload_Template_Parameter_DoubleValue)(nil),
		(*Payload_Template_Parameter_BooleanValue)(nil),
		(*Payload_Template_Parameter_StringValue)(nil),
		(*Payload_Template_Parameter_ExtensionValue)(nil),
	}
}

type Payload_Template_Parameter_ParameterValueExtension struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_Template_Parameter_ParameterValueExtension) Reset() {
	*m = Payload_Template_Parameter_ParameterValueExtension{}
}
func (m *Payload_Template_Parameter_ParameterValueExtension) String() string {
	return proto.CompactTextString(m)
}
func (*Payload_Template_Parameter_ParameterValueExtension) ProtoMessage() {}
func (*Payload_Template_Parameter_ParameterValueExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 0, 0, 0}
}

var extRange_Payload_Template_Parameter_ParameterValueExtension = []proto.ExtensionRange{
	{Start: 1, End: 536870911},
}

func (*Payload_Template_Parameter_ParameterValueExtension) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_Template_Parameter_ParameterValueExtension
}

func (m *Payload_Template_Parameter_ParameterValueExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension.Unmarshal(m, b)
}
func (m *Payload_Template_Parameter_ParameterValueExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension.Marshal(b, m, deterministic)
}
func (m *Payload_Template_Parameter_ParameterValueExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension.Merge(m, src)
}
func (m *Payload_Template_Parameter_ParameterValueExtension) XXX_Size() int {
	return xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension.Size(m)
}
func (m *Payload_Template_Parameter_ParameterValueExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Template_Parameter_ParameterValueExtension proto.InternalMessageInfo

type Payload_DataSet struct {
	NumOfColumns                 *uint64                `protobuf:"varint,1,opt,name=num_of_columns,json=numOfColumns" json:"num_of_columns,omitempty"`
	Columns                      []string               `protobuf:"bytes,2,rep,name=columns" json:"columns,omitempty"`
	Types                        []uint32               `protobuf:"varint,3,rep,name=types" json:"types,omitempty"`
	Rows                         []*Payload_DataSet_Row `protobuf:"bytes,4,rep,name=rows" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}               `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_DataSet) Reset()         { *m = Payload_DataSet{} }
func (m *Payload_DataSet) String() string { return proto.CompactTextString(m) }
func (*Payload_DataSet) ProtoMessage()    {}
func (*Payload_DataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 1}
}

var extRange_Payload_DataSet = []proto.ExtensionRange{
	{Start: 5, End: 536870911},
}

func (*Payload_DataSet) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_DataSet
}

func (m *Payload_DataSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_DataSet.Unmarshal(m, b)
}
func (m *Payload_DataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_DataSet.Marshal(b, m, deterministic)
}
func (m *Payload_DataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_DataSet.Merge(m, src)
}
func (m *Payload_DataSet) XXX_Size() int {
	return xxx_messageInfo_Payload_DataSet.Size(m)
}
func (m *Payload_DataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_DataSet.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_DataSet proto.InternalMessageInfo

func (m *Payload_DataSet) GetNumOfColumns() uint64 {
	if m != nil && m.NumOfColumns != nil {
		return *m.NumOfColumns
	}
	return 0
}

func (m *Payload_DataSet) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Payload_DataSet) GetTypes() []uint32 {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *Payload_DataSet) GetRows() []*Payload_DataSet_Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Payload_DataSet_DataSetValue struct {
	// Types that are valid to be assigned to Value:
	//	*Payload_DataSet_DataSetValue_IntValue
	//	*Payload_DataSet_DataSetValue_LongValue
	//	*Payload_DataSet_DataSetValue_FloatValue
	//	*Payload_DataSet_DataSetValue_DoubleValue
	//	*Payload_DataSet_DataSetValue_BooleanValue
	//	*Payload_DataSet_DataSetValue_StringValue
	//	*Payload_DataSet_DataSetValue_ExtensionValue
	Value                isPayload_DataSet_DataSetValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Payload_DataSet_DataSetValue) Reset()         { *m = Payload_DataSet_DataSetValue{} }
func (m *Payload_DataSet_DataSetValue) String() string { return proto.CompactTextString(m) }
func (*Payload_DataSet_DataSetValue) ProtoMessage()    {}
func (*Payload_DataSet_DataSetValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 1, 0}
}

func (m *Payload_DataSet_DataSetValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_DataSet_DataSetValue.Unmarshal(m, b)
}
func (m *Payload_DataSet_DataSetValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_DataSet_DataSetValue.Marshal(b, m, deterministic)
}
func (m *Payload_DataSet_DataSetValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_DataSet_DataSetValue.Merge(m, src)
}
func (m *Payload_DataSet_DataSetValue) XXX_Size() int {
	return xxx_messageInfo_Payload_DataSet_DataSetValue.Size(m)
}
func (m *Payload_DataSet_DataSetValue) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_DataSet_DataSetValue.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_DataSet_DataSetValue proto.InternalMessageInfo

type isPayload_DataSet_DataSetValue_Value interface {
	isPayload_DataSet_DataSetValue_Value()
}

type Payload_DataSet_DataSetValue_IntValue struct {
	IntValue uint32 `protobuf:"varint,1,opt,name=int_value,json=intValue,oneof"`
}

type Payload_DataSet_DataSetValue_LongValue struct {
	LongValue uint64 `protobuf:"varint,2,opt,name=long_value,json=longValue,oneof"`
}

type Payload_DataSet_DataSetValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,oneof"`
}

type Payload_DataSet_DataSetValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,oneof"`
}

type Payload_DataSet_DataSetValue_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,5,opt,name=boolean_value,json=booleanValue,oneof"`
}

type Payload_DataSet_DataSetValue_StringValue struct {
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,oneof"`
}

type Payload_DataSet_DataSetValue_ExtensionValue struct {
	ExtensionValue *Payload_DataSet_DataSetValue_DataSetValueExtension `protobuf:"bytes,7,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_DataSet_DataSetValue_IntValue) isPayload_DataSet_DataSetValue_Value() {}

func (*Payload_DataSet_DataSetValue_LongValue) isPayload_DataSet_DataSetValue_Value() {}

func (*Payload_DataSet_DataSetValue_FloatValue) isPayload_DataSet_DataSetValue_Value() {}

func (*Payload_DataSet_DataSetValue_DoubleValue) isPayload_DataSet_DataSetValue_Value() {}

func (*Payload_DataSet_DataSetValue_BooleanValue) isPayload_DataSet_DataSetValue_Value() {}

func (*Payload_DataSet_DataSetValue_StringValue) isPayload_DataSet_DataSetValue_Value() {}

func (*Payload_DataSet_DataSetValue_ExtensionValue) isPayload_DataSet_DataSetValue_Value() {}

func (m *Payload_DataSet_DataSetValue) GetValue() isPayload_DataSet_DataSetValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Payload_DataSet_DataSetValue) GetIntValue() uint32 {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Payload_DataSet_DataSetValue) GetLongValue() uint64 {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Payload_DataSet_DataSetValue) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Payload_DataSet_DataSetValue) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Payload_DataSet_DataSetValue) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *Payload_DataSet_DataSetValue) GetStringValue() string {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Payload_DataSet_DataSetValue) GetExtensionValue() *Payload_DataSet_DataSetValue_DataSetValueExtension {
	if x, ok := m.GetValue().(*Payload_DataSet_DataSetValue_ExtensionValue); ok {
		return x.ExtensionValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Payload_DataSet_DataSetValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Payload_DataSet_DataSetValue_IntValue)(nil),
		(*Payload_DataSet_DataSetValue_LongValue)(nil),
		(*Payload_DataSet_DataSetValue_FloatValue)(nil),
		(*Payload_DataSet_DataSetValue_DoubleValue)(nil),
		(*Payload_DataSet_DataSetValue_BooleanValue)(nil),
		(*Payload_DataSet_DataSetValue_StringValue)(nil),
		(*Payload_DataSet_DataSetValue_ExtensionValue)(nil),
	}
}

type Payload_DataSet_DataSetValue_DataSetValueExtension struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) Reset() {
	*m = Payload_DataSet_DataSetValue_DataSetValueExtension{}
}
func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) String() string {
	return proto.CompactTextString(m)
}
func (*Payload_DataSet_DataSetValue_DataSetValueExtension) ProtoMessage() {}
func (*Payload_DataSet_DataSetValue_DataSetValueExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 1, 0, 0}
}

var extRange_Payload_DataSet_DataSetValue_DataSetValueExtension = []proto.ExtensionRange{
	{Start: 1, End: 536870911},
}

func (*Payload_DataSet_DataSetValue_DataSetValueExtension) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_DataSet_DataSetValue_DataSetValueExtension
}

func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension.Unmarshal(m, b)
}
func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension.Marshal(b, m, deterministic)
}
func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension.Merge(m, src)
}
func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) XXX_Size() int {
	return xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension.Size(m)
}
func (m *Payload_DataSet_DataSetValue_DataSetValueExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_DataSet_DataSetValue_DataSetValueExtension proto.InternalMessageInfo

type Payload_DataSet_Row struct {
	Elements                     []*Payload_DataSet_DataSetValue `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                        `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_DataSet_Row) Reset()         { *m = Payload_DataSet_Row{} }
func (m *Payload_DataSet_Row) String() string { return proto.CompactTextString(m) }
func (*Payload_DataSet_Row) ProtoMessage()    {}
func (*Payload_DataSet_Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 1, 1}
}

var extRange_Payload_DataSet_Row = []proto.ExtensionRange{
	{Start: 2, End: 536870911},
}

func (*Payload_DataSet_Row) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_DataSet_Row
}

func (m *Payload_DataSet_Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_DataSet_Row.Unmarshal(m, b)
}
func (m *Payload_DataSet_Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_DataSet_Row.Marshal(b, m, deterministic)
}
func (m *Payload_DataSet_Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_DataSet_Row.Merge(m, src)
}
func (m *Payload_DataSet_Row) XXX_Size() int {
	return xxx_messageInfo_Payload_DataSet_Row.Size(m)
}
func (m *Payload_DataSet_Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_DataSet_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_DataSet_Row proto.InternalMessageInfo

func (m *Payload_DataSet_Row) GetElements() []*Payload_DataSet_DataSetValue {
	if m != nil {
		return m.Elements
	}
	return nil
}

type Payload_PropertyValue struct {
	Type   *uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	IsNull *bool   `protobuf:"varint,2,opt,name=is_null,json=isNull" json:"is_null,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Payload_PropertyValue_IntValue
	//	*Payload_PropertyValue_LongValue
	//	*Payload_PropertyValue_FloatValue
	//	*Payload_PropertyValue_DoubleValue
	//	*Payload_PropertyValue_BooleanValue
	//	*Payload_PropertyValue_StringValue
	//	*Payload_PropertyValue_PropertysetValue
	//	*Payload_PropertyValue_PropertysetsValue
	//	*Payload_PropertyValue_ExtensionValue
	Value                isPayload_PropertyValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Payload_PropertyValue) Reset()         { *m = Payload_PropertyValue{} }
func (m *Payload_PropertyValue) String() string { return proto.CompactTextString(m) }
func (*Payload_PropertyValue) ProtoMessage()    {}
func (*Payload_PropertyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 2}
}

func (m *Payload_PropertyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_PropertyValue.Unmarshal(m, b)
}
func (m *Payload_PropertyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_PropertyValue.Marshal(b, m, deterministic)
}
func (m *Payload_PropertyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_PropertyValue.Merge(m, src)
}
func (m *Payload_PropertyValue) XXX_Size() int {
	return xxx_messageInfo_Payload_PropertyValue.Size(m)
}
func (m *Payload_PropertyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_PropertyValue.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_PropertyValue proto.InternalMessageInfo

func (m *Payload_PropertyValue) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Payload_PropertyValue) GetIsNull() bool {
	if m != nil && m.IsNull != nil {
		return *m.IsNull
	}
	return false
}

type isPayload_PropertyValue_Value interface {
	isPayload_PropertyValue_Value()
}

type Payload_PropertyValue_IntValue struct {
	IntValue uint32 `protobuf:"varint,3,opt,name=int_value,json=intValue,oneof"`
}

type Payload_PropertyValue_LongValue struct {
	LongValue uint64 `protobuf:"varint,4,opt,name=long_value,json=longValue,oneof"`
}

type Payload_PropertyValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,5,opt,name=float_value,json=floatValue,oneof"`
}

type Payload_PropertyValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue,oneof"`
}

type Payload_PropertyValue_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,7,opt,name=boolean_value,json=booleanValue,oneof"`
}

type Payload_PropertyValue_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,oneof"`
}

type Payload_PropertyValue_PropertysetValue struct {
	PropertysetValue *Payload_PropertySet `protobuf:"bytes,9,opt,name=propertyset_value,json=propertysetValue,oneof"`
}

type Payload_PropertyValue_PropertysetsValue struct {
	PropertysetsValue *Payload_PropertySetList `protobuf:"bytes,10,opt,name=propertysets_value,json=propertysetsValue,oneof"`
}

type Payload_PropertyValue_ExtensionValue struct {
	ExtensionValue *Payload_PropertyValue_PropertyValueExtension `protobuf:"bytes,11,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_PropertyValue_IntValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_LongValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_FloatValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_DoubleValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_BooleanValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_StringValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_PropertysetValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_PropertysetsValue) isPayload_PropertyValue_Value() {}

func (*Payload_PropertyValue_ExtensionValue) isPayload_PropertyValue_Value() {}

func (m *Payload_PropertyValue) GetValue() isPayload_PropertyValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Payload_PropertyValue) GetIntValue() uint32 {
	if x, ok := m.GetValue().(*Payload_PropertyValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Payload_PropertyValue) GetLongValue() uint64 {
	if x, ok := m.GetValue().(*Payload_PropertyValue_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Payload_PropertyValue) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*Payload_PropertyValue_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Payload_PropertyValue) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Payload_PropertyValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Payload_PropertyValue) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*Payload_PropertyValue_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *Payload_PropertyValue) GetStringValue() string {
	if x, ok := m.GetValue().(*Payload_PropertyValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Payload_PropertyValue) GetPropertysetValue() *Payload_PropertySet {
	if x, ok := m.GetValue().(*Payload_PropertyValue_PropertysetValue); ok {
		return x.PropertysetValue
	}
	return nil
}

func (m *Payload_PropertyValue) GetPropertysetsValue() *Payload_PropertySetList {
	if x, ok := m.GetValue().(*Payload_PropertyValue_PropertysetsValue); ok {
		return x.PropertysetsValue
	}
	return nil
}

func (m *Payload_PropertyValue) GetExtensionValue() *Payload_PropertyValue_PropertyValueExtension {
	if x, ok := m.GetValue().(*Payload_PropertyValue_ExtensionValue); ok {
		return x.ExtensionValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Payload_PropertyValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Payload_PropertyValue_IntValue)(nil),
		(*Payload_PropertyValue_LongValue)(nil),
		(*Payload_PropertyValue_FloatValue)(nil),
		(*Payload_PropertyValue_DoubleValue)(nil),
		(*Payload_PropertyValue_BooleanValue)(nil),
		(*Payload_PropertyValue_StringValue)(nil),
		(*Payload_PropertyValue_PropertysetValue)(nil),
		(*Payload_PropertyValue_PropertysetsValue)(nil),
		(*Payload_PropertyValue_ExtensionValue)(nil),
	}
}

type Payload_PropertyValue_PropertyValueExtension struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_PropertyValue_PropertyValueExtension) Reset() {
	*m = Payload_PropertyValue_PropertyValueExtension{}
}
func (m *Payload_PropertyValue_PropertyValueExtension) String() string {
	return proto.CompactTextString(m)
}
func (*Payload_PropertyValue_PropertyValueExtension) ProtoMessage() {}
func (*Payload_PropertyValue_PropertyValueExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 2, 0}
}

var extRange_Payload_PropertyValue_PropertyValueExtension = []proto.ExtensionRange{
	{Start: 1, End: 536870911},
}

func (*Payload_PropertyValue_PropertyValueExtension) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_PropertyValue_PropertyValueExtension
}

func (m *Payload_PropertyValue_PropertyValueExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension.Unmarshal(m, b)
}
func (m *Payload_PropertyValue_PropertyValueExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension.Marshal(b, m, deterministic)
}
func (m *Payload_PropertyValue_PropertyValueExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension.Merge(m, src)
}
func (m *Payload_PropertyValue_PropertyValueExtension) XXX_Size() int {
	return xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension.Size(m)
}
func (m *Payload_PropertyValue_PropertyValueExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_PropertyValue_PropertyValueExtension proto.InternalMessageInfo

type Payload_PropertySet struct {
	Keys                         []string                 `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Values                       []*Payload_PropertyValue `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                 `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_PropertySet) Reset()         { *m = Payload_PropertySet{} }
func (m *Payload_PropertySet) String() string { return proto.CompactTextString(m) }
func (*Payload_PropertySet) ProtoMessage()    {}
func (*Payload_PropertySet) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 3}
}

var extRange_Payload_PropertySet = []proto.ExtensionRange{
	{Start: 3, End: 536870911},
}

func (*Payload_PropertySet) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_PropertySet
}

func (m *Payload_PropertySet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_PropertySet.Unmarshal(m, b)
}
func (m *Payload_PropertySet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_PropertySet.Marshal(b, m, deterministic)
}
func (m *Payload_PropertySet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_PropertySet.Merge(m, src)
}
func (m *Payload_PropertySet) XXX_Size() int {
	return xxx_messageInfo_Payload_PropertySet.Size(m)
}
func (m *Payload_PropertySet) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_PropertySet.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_PropertySet proto.InternalMessageInfo

func (m *Payload_PropertySet) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Payload_PropertySet) GetValues() []*Payload_PropertyValue {
	if m != nil {
		return m.Values
	}
	return nil
}

type Payload_PropertySetList struct {
	Propertyset                  []*Payload_PropertySet `protobuf:"bytes,1,rep,name=propertyset" json:"propertyset,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}               `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_PropertySetList) Reset()         { *m = Payload_PropertySetList{} }
func (m *Payload_PropertySetList) String() string { return proto.CompactTextString(m) }
func (*Payload_PropertySetList) ProtoMessage()    {}
func (*Payload_PropertySetList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 4}
}

var extRange_Payload_PropertySetList = []proto.ExtensionRange{
	{Start: 2, End: 536870911},
}

func (*Payload_PropertySetList) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_PropertySetList
}

func (m *Payload_PropertySetList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_PropertySetList.Unmarshal(m, b)
}
func (m *Payload_PropertySetList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_PropertySetList.Marshal(b, m, deterministic)
}
func (m *Payload_PropertySetList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_PropertySetList.Merge(m, src)
}
func (m *Payload_PropertySetList) XXX_Size() int {
	return xxx_messageInfo_Payload_PropertySetList.Size(m)
}
func (m *Payload_PropertySetList) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_PropertySetList.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_PropertySetList proto.InternalMessageInfo

func (m *Payload_PropertySetList) GetPropertyset() []*Payload_PropertySet {
	if m != nil {
		return m.Propertyset
	}
	return nil
}

type Payload_MetaData struct {
	IsMultiPart                  *bool    `protobuf:"varint,1,opt,name=is_multi_part,json=isMultiPart" json:"is_multi_part,omitempty"`
	ContentType                  *string  `protobuf:"bytes,2,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Size                         *uint64  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Seq                          *uint64  `protobuf:"varint,4,opt,name=seq" json:"seq,omitempty"`
	FileName                     *string  `protobuf:"bytes,5,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	FileType                     *string  `protobuf:"bytes,6,opt,name=file_type,json=fileType" json:"file_type,omitempty"`
	Md5                          *string  `protobuf:"bytes,7,opt,name=md5" json:"md5,omitempty"`
	Description                  *string  `protobuf:"bytes,8,opt,name=description" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_MetaData) Reset()         { *m = Payload_MetaData{} }
func (m *Payload_MetaData) String() string { return proto.CompactTextString(m) }
func (*Payload_MetaData) ProtoMessage()    {}
func (*Payload_MetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 5}
}

var extRange_Payload_MetaData = []proto.ExtensionRange{
	{Start: 9, End: 536870911},
}

func (*Payload_MetaData) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_MetaData
}

func (m *Payload_MetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_MetaData.Unmarshal(m, b)
}
func (m *Payload_MetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_MetaData.Marshal(b, m, deterministic)
}
func (m *Payload_MetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_MetaData.Merge(m, src)
}
func (m *Payload_MetaData) XXX_Size() int {
	return xxx_messageInfo_Payload_MetaData.Size(m)
}
func (m *Payload_MetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_MetaData.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_MetaData proto.InternalMessageInfo

func (m *Payload_MetaData) GetIsMultiPart() bool {
	if m != nil && m.IsMultiPart != nil {
		return *m.IsMultiPart
	}
	return false
}

func (m *Payload_MetaData) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *Payload_MetaData) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *Payload_MetaData) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *Payload_MetaData) GetFileName() string {
	if m != nil && m.FileName != nil {
		return *m.FileName
	}
	return ""
}

func (m *Payload_MetaData) GetFileType() string {
	if m != nil && m.FileType != nil {
		return *m.FileType
	}
	return ""
}

func (m *Payload_MetaData) GetMd5() string {
	if m != nil && m.Md5 != nil {
		return *m.Md5
	}
	return ""
}

func (m *Payload_MetaData) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type Payload_Metric struct {
	Name         *string              `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Alias        *uint64              `protobuf:"varint,2,opt,name=alias" json:"alias,omitempty"`
	Timestamp    *uint64              `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	Datatype     *uint32              `protobuf:"varint,4,opt,name=datatype" json:"datatype,omitempty"`
	IsHistorical *bool                `protobuf:"varint,5,opt,name=is_historical,json=isHistorical" json:"is_historical,omitempty"`
	IsTransient  *bool                `protobuf:"varint,6,opt,name=is_transient,json=isTransient" json:"is_transient,omitempty"`
	IsNull       *bool                `protobuf:"varint,7,opt,name=is_null,json=isNull" json:"is_null,omitempty"`
	Metadata     *Payload_MetaData    `protobuf:"bytes,8,opt,name=metadata" json:"metadata,omitempty"`
	Properties   *Payload_PropertySet `protobuf:"bytes,9,opt,name=properties" json:"properties,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Payload_Metric_IntValue
	//	*Payload_Metric_LongValue
	//	*Payload_Metric_FloatValue
	//	*Payload_Metric_DoubleValue
	//	*Payload_Metric_BooleanValue
	//	*Payload_Metric_StringValue
	//	*Payload_Metric_BytesValue
	//	*Payload_Metric_DatasetValue
	//	*Payload_Metric_TemplateValue
	//	*Payload_Metric_ExtensionValue
	Value                isPayload_Metric_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Payload_Metric) Reset()         { *m = Payload_Metric{} }
func (m *Payload_Metric) String() string { return proto.CompactTextString(m) }
func (*Payload_Metric) ProtoMessage()    {}
func (*Payload_Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 6}
}

func (m *Payload_Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Metric.Unmarshal(m, b)
}
func (m *Payload_Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Metric.Marshal(b, m, deterministic)
}
func (m *Payload_Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Metric.Merge(m, src)
}
func (m *Payload_Metric) XXX_Size() int {
	return xxx_messageInfo_Payload_Metric.Size(m)
}
func (m *Payload_Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Metric proto.InternalMessageInfo

func (m *Payload_Metric) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Payload_Metric) GetAlias() uint64 {
	if m != nil && m.Alias != nil {
		return *m.Alias
	}
	return 0
}

func (m *Payload_Metric) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Payload_Metric) GetDatatype() uint32 {
	if m != nil && m.Datatype != nil {
		return *m.Datatype
	}
	return 0
}

func (m *Payload_Metric) GetIsHistorical() bool {
	if m != nil && m.IsHistorical != nil {
		return *m.IsHistorical
	}
	return false
}

func (m *Payload_Metric) GetIsTransient() bool {
	if m != nil && m.IsTransient != nil {
		return *m.IsTransient
	}
	return false
}

func (m *Payload_Metric) GetIsNull() bool {
	if m != nil && m.IsNull != nil {
		return *m.IsNull
	}
	return false
}

func (m *Payload_Metric) GetMetadata() *Payload_MetaData {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Payload_Metric) GetProperties() *Payload_PropertySet {
	if m != nil {
		return m.Properties
	}
	return nil
}

type isPayload_Metric_Value interface {
	isPayload_Metric_Value()
}

type Payload_Metric_IntValue struct {
	IntValue uint32 `protobuf:"varint,10,opt,name=int_value,json=intValue,oneof"`
}

type Payload_Metric_LongValue struct {
	LongValue uint64 `protobuf:"varint,11,opt,name=long_value,json=longValue,oneof"`
}

type Payload_Metric_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,12,opt,name=float_value,json=floatValue,oneof"`
}

type Payload_Metric_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,13,opt,name=double_value,json=doubleValue,oneof"`
}

type Payload_Metric_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,14,opt,name=boolean_value,json=booleanValue,oneof"`
}

type Payload_Metric_StringValue struct {
	StringValue string `protobuf:"bytes,15,opt,name=string_value,json=stringValue,oneof"`
}

type Payload_Metric_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,16,opt,name=bytes_value,json=bytesValue,oneof"`
}

type Payload_Metric_DatasetValue struct {
	DatasetValue *Payload_DataSet `protobuf:"bytes,17,opt,name=dataset_value,json=datasetValue,oneof"`
}

type Payload_Metric_TemplateValue struct {
	TemplateValue *Payload_Template `protobuf:"bytes,18,opt,name=template_value,json=templateValue,oneof"`
}

type Payload_Metric_ExtensionValue struct {
	ExtensionValue *Payload_Metric_MetricValueExtension `protobuf:"bytes,19,opt,name=extension_value,json=extensionValue,oneof"`
}

func (*Payload_Metric_IntValue) isPayload_Metric_Value() {}

func (*Payload_Metric_LongValue) isPayload_Metric_Value() {}

func (*Payload_Metric_FloatValue) isPayload_Metric_Value() {}

func (*Payload_Metric_DoubleValue) isPayload_Metric_Value() {}

func (*Payload_Metric_BooleanValue) isPayload_Metric_Value() {}

func (*Payload_Metric_StringValue) isPayload_Metric_Value() {}

func (*Payload_Metric_BytesValue) isPayload_Metric_Value() {}

func (*Payload_Metric_DatasetValue) isPayload_Metric_Value() {}

func (*Payload_Metric_TemplateValue) isPayload_Metric_Value() {}

func (*Payload_Metric_ExtensionValue) isPayload_Metric_Value() {}

func (m *Payload_Metric) GetValue() isPayload_Metric_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Payload_Metric) GetIntValue() uint32 {
	if x, ok := m.GetValue().(*Payload_Metric_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Payload_Metric) GetLongValue() uint64 {
	if x, ok := m.GetValue().(*Payload_Metric_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Payload_Metric) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*Payload_Metric_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Payload_Metric) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Payload_Metric_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Payload_Metric) GetBooleanValue() bool {
	if x, ok := m.GetValue().(*Payload_Metric_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (m *Payload_Metric) GetStringValue() string {
	if x, ok := m.GetValue().(*Payload_Metric_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Payload_Metric) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*Payload_Metric_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *Payload_Metric) GetDatasetValue() *Payload_DataSet {
	if x, ok := m.GetValue().(*Payload_Metric_DatasetValue); ok {
		return x.DatasetValue
	}
	return nil
}

func (m *Payload_Metric) GetTemplateValue() *Payload_Template {
	if x, ok := m.GetValue().(*Payload_Metric_TemplateValue); ok {
		return x.TemplateValue
	}
	return nil
}

func (m *Payload_Metric) GetExtensionValue() *Payload_Metric_MetricValueExtension {
	if x, ok := m.GetValue().(*Payload_Metric_ExtensionValue); ok {
		return x.ExtensionValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Payload_Metric) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Payload_Metric_IntValue)(nil),
		(*Payload_Metric_LongValue)(nil),
		(*Payload_Metric_FloatValue)(nil),
		(*Payload_Metric_DoubleValue)(nil),
		(*Payload_Metric_BooleanValue)(nil),
		(*Payload_Metric_StringValue)(nil),
		(*Payload_Metric_BytesValue)(nil),
		(*Payload_Metric_DatasetValue)(nil),
		(*Payload_Metric_TemplateValue)(nil),
		(*Payload_Metric_ExtensionValue)(nil),
	}
}

type Payload_Metric_MetricValueExtension struct {
	XXX_NoUnkeyedLiteral         struct{} `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *Payload_Metric_MetricValueExtension) Reset()         { *m = Payload_Metric_MetricValueExtension{} }
func (m *Payload_Metric_MetricValueExtension) String() string { return proto.CompactTextString(m) }
func (*Payload_Metric_MetricValueExtension) ProtoMessage()    {}
func (*Payload_Metric_MetricValueExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ebbf56186e73398, []int{0, 6, 0}
}

var extRange_Payload_Metric_MetricValueExtension = []proto.ExtensionRange{
	{Start: 1, End: 536870911},
}

func (*Payload_Metric_MetricValueExtension) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Payload_Metric_MetricValueExtension
}

func (m *Payload_Metric_MetricValueExtension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload_Metric_MetricValueExtension.Unmarshal(m, b)
}
func (m *Payload_Metric_MetricValueExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload_Metric_MetricValueExtension.Marshal(b, m, deterministic)
}
func (m *Payload_Metric_MetricValueExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload_Metric_MetricValueExtension.Merge(m, src)
}
func (m *Payload_Metric_MetricValueExtension) XXX_Size() int {
	return xxx_messageInfo_Payload_Metric_MetricValueExtension.Size(m)
}
func (m *Payload_Metric_MetricValueExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload_Metric_MetricValueExtension.DiscardUnknown(m)
}

var xxx_messageInfo_Payload_Metric_MetricValueExtension proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Payload)(nil), "sparkplug.Payload")
	proto.RegisterType((*Payload_Template)(nil), "sparkplug.Payload.Template")
	proto.RegisterType((*Payload_Template_Parameter)(nil), "sparkplug.Payload.Template.Parameter")
	proto.RegisterType((*Payload_Template_Parameter_ParameterValueExtension)(nil), "sparkplug.Payload.Template.Parameter.ParameterValueExtension")
	proto.RegisterType((*Payload_DataSet)(nil), "sparkplug.Payload.DataSet")
	proto.RegisterType((*Payload_DataSet_DataSetValue)(nil), "sparkplug.Payload.DataSet.DataSetValue")
	proto.RegisterType((*Payload_DataSet_DataSetValue_DataSetValueExtension)(nil), "sparkplug.Payload.DataSet.DataSetValue.DataSetValueExtension")
	proto.RegisterType((*Payload_DataSet_Row)(nil), "sparkplug.Payload.DataSet.Row")
	proto.RegisterType((*Payload_PropertyValue)(nil), "sparkplug.Payload.PropertyValue")
	proto.RegisterType((*Payload_PropertyValue_PropertyValueExtension)(nil), "sparkplug.Payload.PropertyValue.PropertyValueExtension")
	proto.RegisterType((*Payload_PropertySet)(nil), "sparkplug.Payload.PropertySet")
	proto.RegisterType((*Payload_PropertySetList)(nil), "sparkplug.Payload.PropertySetList")
	proto.RegisterType((*Payload_MetaData)(nil), "sparkplug.Payload.MetaData")
	proto.RegisterType((*Payload_Metric)(nil), "sparkplug.Payload.Metric")
	proto.RegisterType((*Payload_Metric_MetricValueExtension)(nil), "sparkplug.Payload.Metric.MetricValueExtension")
}

func init() { proto.RegisterFile("sparkplug.proto", fileDescriptor_3ebbf56186e73398) }

var fileDescriptor_3ebbf56186e73398 = []byte{
	// 1114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0x4d, 0x73, 0x1b, 0x35,
	0x18, 0xf6, 0xda, 0x6b, 0x5b, 0xfb, 0xae, 0x9d, 0xa4, 0xa2, 0x50, 0xd7, 0xe5, 0xc3, 0x49, 0xe8,
	0xe0, 0xf1, 0xc1, 0x87, 0x30, 0x4c, 0xb9, 0xc0, 0x00, 0x4d, 0x67, 0x7c, 0x20, 0x25, 0xa3, 0x64,
	0x98, 0xe1, 0xc0, 0x78, 0x94, 0x58, 0x6e, 0x35, 0xdd, 0x2f, 0x56, 0xda, 0x06, 0x73, 0xca, 0x8f,
	0xe0, 0xce, 0xaf, 0xe1, 0xc6, 0x6f, 0x81, 0x23, 0x1c, 0x19, 0x7d, 0xec, 0x7a, 0xdd, 0x6e, 0xec,
	0x1d, 0x8e, 0x9c, 0x2c, 0x3d, 0x7e, 0xf4, 0xec, 0xab, 0x57, 0x8f, 0x5e, 0xbd, 0xb0, 0x2f, 0x12,
	0x9a, 0xbe, 0x4a, 0x82, 0xec, 0xc5, 0x34, 0x49, 0x63, 0x19, 0x63, 0xaf, 0x00, 0x8e, 0xfe, 0x7e,
	0x08, 0xdd, 0x73, 0xba, 0x0a, 0x62, 0xba, 0xc0, 0xef, 0x83, 0x27, 0x79, 0xc8, 0x84, 0xa4, 0x61,
	0x32, 0x70, 0x46, 0xce, 0xd8, 0x25, 0x6b, 0x00, 0x7f, 0x0a, 0xdd, 0x90, 0xc9, 0x94, 0x5f, 0x8b,
	0x41, 0x73, 0xd4, 0x1a, 0xfb, 0x27, 0x0f, 0xa7, 0x6b, 0x5d, 0x2b, 0x31, 0x3d, 0xd3, 0x0c, 0x92,
	0x33, 0xf1, 0x01, 0xb4, 0x04, 0xfb, 0x69, 0xd0, 0xd2, 0x62, 0x6a, 0x88, 0x31, 0xb8, 0x59, 0xc6,
	0x17, 0x03, 0x77, 0xe4, 0x8c, 0x3d, 0xa2, 0xc7, 0x0a, 0xbb, 0x8a, 0x17, 0xab, 0x41, 0x7b, 0xe4,
	0x8c, 0x7b, 0x44, 0x8f, 0x87, 0xbf, 0xb6, 0x01, 0x5d, 0xb2, 0x30, 0x09, 0xa8, 0x64, 0x78, 0x00,
	0xdd, 0xd7, 0x2c, 0x15, 0x3c, 0x8e, 0x74, 0x5c, 0x1e, 0xc9, 0xa7, 0xff, 0x2d, 0xaa, 0x67, 0x00,
	0x09, 0x4d, 0x69, 0xc8, 0x24, 0x4b, 0xc5, 0xa0, 0xa5, 0xd7, 0x3d, 0xae, 0x58, 0x97, 0x7f, 0x7f,
	0x7a, 0x9e, 0xb3, 0x49, 0x69, 0x21, 0x3e, 0x84, 0x9e, 0xb4, 0x8c, 0x79, 0xca, 0x96, 0x76, 0x4b,
	0x7e, 0x8e, 0x11, 0xb6, 0xc4, 0xc7, 0xd0, 0xe7, 0x62, 0xbe, 0x60, 0x4b, 0x1e, 0x71, 0xa9, 0xc2,
	0x57, 0x5b, 0x44, 0xa4, 0xc7, 0xc5, 0x69, 0x81, 0x0d, 0x7f, 0x6b, 0x81, 0x57, 0x7c, 0x41, 0x25,
	0x23, 0xa2, 0x21, 0xb3, 0x1b, 0xd5, 0x63, 0x85, 0xc9, 0x55, 0xc2, 0x06, 0xcd, 0x91, 0x33, 0xee,
	0x13, 0x3d, 0xc6, 0x1f, 0x80, 0xc7, 0x23, 0x39, 0x7f, 0x4d, 0x83, 0x8c, 0xe9, 0x04, 0xf7, 0x67,
	0x0d, 0x82, 0x78, 0x24, 0xbf, 0x57, 0x08, 0xfe, 0x08, 0x20, 0x88, 0xa3, 0x17, 0xf6, 0x7f, 0x15,
	0x9a, 0x3b, 0x6b, 0x10, 0x4f, 0x61, 0x86, 0x70, 0x08, 0xfe, 0x32, 0x88, 0x69, 0xae, 0xa0, 0x02,
	0x6b, 0xce, 0x1a, 0x04, 0x34, 0x68, 0x28, 0xc7, 0xd0, 0x5b, 0xc4, 0xd9, 0x55, 0xc0, 0x2c, 0xa7,
	0x33, 0x72, 0xc6, 0xce, 0xac, 0x41, 0x7c, 0x83, 0x1a, 0xd2, 0x63, 0xe8, 0x5f, 0xc5, 0x71, 0xc0,
	0x68, 0x64, 0x59, 0x5d, 0xb5, 0xc5, 0x59, 0x83, 0xf4, 0x2c, 0x5c, 0x68, 0x09, 0x99, 0xf2, 0x22,
	0x22, 0xa4, 0xb6, 0xa7, 0xb4, 0x0c, 0x6a, 0x48, 0x2f, 0x61, 0x9f, 0xfd, 0x2c, 0x59, 0xa4, 0x8e,
	0xd6, 0xf2, 0xbc, 0x91, 0x33, 0xf6, 0x4f, 0xbe, 0xa8, 0x75, 0x3a, 0xeb, 0x91, 0x96, 0x7b, 0x96,
	0x4b, 0xcd, 0x1a, 0x64, 0xaf, 0xd0, 0xd5, 0x7f, 0x0d, 0x8f, 0xe1, 0xc1, 0x1d, 0xe4, 0x09, 0x42,
	0xce, 0xc1, 0xed, 0xed, 0xed, 0x6d, 0xf3, 0x9b, 0x2e, 0xb4, 0x75, 0x10, 0x13, 0x84, 0x3a, 0x06,
	0x1a, 0xfe, 0xe9, 0x42, 0xf7, 0x94, 0x4a, 0x7a, 0xc1, 0x24, 0xfe, 0x18, 0xf6, 0xa2, 0x2c, 0x9c,
	0xc7, 0xcb, 0xf9, 0x75, 0x1c, 0x64, 0x61, 0x24, 0xec, 0xa5, 0xe9, 0x45, 0x59, 0xf8, 0xdd, 0xf2,
	0xa9, 0xc1, 0x94, 0x77, 0xf3, 0xbf, 0x95, 0x43, 0x3d, 0x92, 0x4f, 0xf1, 0x7d, 0x68, 0xab, 0x93,
	0x34, 0x0e, 0xec, 0x13, 0x33, 0xc1, 0x27, 0xe0, 0xa6, 0xf1, 0x8d, 0x18, 0xb8, 0xda, 0x96, 0x1f,
	0x56, 0x6c, 0xdc, 0x7e, 0x7f, 0x4a, 0xe2, 0x1b, 0xa2, 0xb9, 0xc3, 0x7f, 0x9a, 0xd0, 0xb3, 0xa8,
	0x49, 0xe4, 0x86, 0x39, 0x9c, 0x1d, 0xe6, 0x68, 0xee, 0x34, 0x47, 0xab, 0x86, 0x39, 0xdc, 0x5a,
	0xe6, 0x68, 0xd7, 0x32, 0x47, 0xa7, 0xa6, 0x39, 0xba, 0x77, 0x9a, 0x23, 0xcf, 0x51, 0x39, 0x2b,
	0x1b, 0x93, 0x6d, 0xe6, 0x38, 0x84, 0x77, 0x2b, 0xa9, 0x15, 0xd6, 0x18, 0x5e, 0x42, 0x8b, 0xc4,
	0x37, 0xf8, 0x29, 0x20, 0x16, 0xb0, 0x90, 0x45, 0x52, 0xb9, 0x40, 0x9d, 0xdc, 0x27, 0x35, 0xa3,
	0x22, 0xc5, 0xc2, 0x09, 0x42, 0x4d, 0x23, 0x3f, 0x41, 0xa8, 0x6d, 0x0d, 0xf7, 0xbb, 0x0b, 0xfd,
	0xf3, 0x34, 0x4e, 0x58, 0x2a, 0x57, 0x26, 0x0f, 0x79, 0x31, 0x70, 0x4a, 0xc5, 0xe0, 0x01, 0x74,
	0xb9, 0x98, 0x47, 0x59, 0x10, 0xe8, 0xd3, 0x44, 0xa4, 0xc3, 0xc5, 0xf3, 0x2c, 0x08, 0xfe, 0x97,
	0x55, 0xe2, 0x0c, 0xee, 0x25, 0x36, 0x23, 0x82, 0xc9, 0x8d, 0x3a, 0x51, 0x75, 0x5d, 0xf2, 0xec,
	0x5d, 0x30, 0x39, 0x6b, 0x90, 0x83, 0xd2, 0x52, 0x23, 0x77, 0x01, 0xb8, 0x84, 0x09, 0xab, 0x07,
	0x5a, 0xef, 0x68, 0xbb, 0xde, 0xb7, 0x5c, 0x28, 0xcd, 0x72, 0x38, 0xc2, 0x88, 0x5e, 0xbd, 0x6d,
	0x56, 0x5f, 0x2b, 0x3e, 0xd9, 0xa2, 0x68, 0x5c, 0xba, 0x31, 0xdb, 0x66, 0xd3, 0x23, 0x78, 0xaf,
	0x9a, 0x5b, 0xe5, 0x53, 0x06, 0x7e, 0x29, 0x70, 0x65, 0xa2, 0x57, 0x6c, 0x65, 0xbc, 0xea, 0x11,
	0x3d, 0xc6, 0x9f, 0x43, 0x47, 0x73, 0xf3, 0xa7, 0x74, 0xb4, 0x2b, 0x54, 0x62, 0xf9, 0x13, 0x84,
	0x5a, 0xd6, 0xae, 0x3f, 0xc2, 0xfe, 0x1b, 0xf9, 0xc1, 0x5f, 0x81, 0x5f, 0xca, 0x8f, 0xbd, 0x1d,
	0x3b, 0x0e, 0x8a, 0x94, 0x97, 0xac, 0xef, 0xc5, 0xf0, 0x2f, 0x07, 0xd0, 0x19, 0x93, 0x54, 0x5d,
	0x20, 0x7c, 0xa4, 0x1f, 0xd7, 0x30, 0x0b, 0x24, 0x9f, 0x27, 0x34, 0x95, 0xfa, 0x46, 0x20, 0xe2,
	0x73, 0x71, 0xa6, 0xb0, 0x73, 0x9a, 0x4a, 0xf5, 0x46, 0x5f, 0xc7, 0x91, 0x64, 0x91, 0x9c, 0x17,
	0x2f, 0xa8, 0x47, 0x7c, 0x8b, 0x5d, 0xaa, 0xbb, 0x83, 0xc1, 0x15, 0xfc, 0x17, 0x66, 0x9b, 0x14,
	0x3d, 0xce, 0xfb, 0x16, 0x77, 0xdd, 0xb7, 0x3c, 0x02, 0x6f, 0xc9, 0x03, 0x36, 0xd7, 0x6f, 0x73,
	0x5b, 0xab, 0x20, 0x05, 0x3c, 0x57, 0xef, 0x73, 0xfe, 0xa7, 0xfe, 0x44, 0x67, 0xfd, 0xa7, 0xd6,
	0x3f, 0x80, 0x56, 0xb8, 0xf8, 0x4c, 0x1b, 0xde, 0x23, 0x6a, 0x88, 0x47, 0xe0, 0x2f, 0x98, 0xb8,
	0x4e, 0x79, 0xa2, 0x7b, 0x02, 0x64, 0x62, 0x2a, 0x41, 0x13, 0x84, 0x3c, 0xbb, 0xe3, 0x3f, 0x3a,
	0xd0, 0x31, 0xfd, 0x4b, 0x65, 0x67, 0x70, 0x1f, 0xda, 0x34, 0xe0, 0x54, 0x98, 0x22, 0x4e, 0xcc,
	0x64, 0xb3, 0x93, 0x6b, 0xbd, 0xd9, 0xc9, 0x0d, 0x01, 0x2d, 0xa8, 0xa4, 0x3a, 0x58, 0x57, 0x17,
	0x91, 0x62, 0x6e, 0x1b, 0x96, 0x97, 0x5c, 0xc8, 0x38, 0xe5, 0xd7, 0x34, 0x58, 0x37, 0x2c, 0xb3,
	0x02, 0x53, 0x49, 0xe5, 0x62, 0x2e, 0x53, 0x1a, 0x09, 0xce, 0x22, 0xa9, 0x77, 0xac, 0xf3, 0x7e,
	0x99, 0x43, 0xe5, 0x82, 0xd4, 0xdd, 0x28, 0x48, 0x4f, 0x00, 0x85, 0x4c, 0x52, 0xf5, 0x41, 0xbd,
	0x71, 0xff, 0xe4, 0x51, 0x75, 0xc7, 0xa6, 0xcf, 0x98, 0x14, 0x64, 0xfc, 0x25, 0x80, 0xf5, 0x04,
	0x67, 0xa2, 0xde, 0x75, 0x27, 0xa5, 0x15, 0x9b, 0x95, 0x10, 0x76, 0x54, 0x42, 0x7f, 0x67, 0x25,
	0xec, 0xd5, 0xa8, 0x84, 0xfd, 0x5a, 0x95, 0x70, 0xaf, 0x56, 0x25, 0xdc, 0xaf, 0xaa, 0x84, 0x87,
	0xe0, 0x5f, 0xad, 0x24, 0xcb, 0x6b, 0xd6, 0x81, 0xea, 0x9f, 0x55, 0x4c, 0x1a, 0x34, 0x94, 0xaf,
	0xa1, 0xaf, 0xd2, 0xb7, 0x2e, 0x94, 0xf7, 0x74, 0xe6, 0x86, 0x77, 0xbf, 0x4e, 0x2a, 0x14, 0xbb,
	0xc4, 0x48, 0x9c, 0xc2, 0x5e, 0xd1, 0xe7, 0x1a, 0x0d, 0x7c, 0xe7, 0xc1, 0xe5, 0x4d, 0xd9, 0xac,
	0x41, 0xfa, 0xf9, 0x22, 0xa3, 0xf2, 0xc3, 0xdb, 0x15, 0xf1, 0x1d, 0x2d, 0x33, 0xbd, 0xb3, 0x63,
	0xb7, 0x3f, 0x3b, 0x0b, 0xe1, 0x08, 0xee, 0x57, 0x31, 0xb7, 0x76, 0x72, 0xff, 0x06, 0x00, 0x00,
	0xff, 0xff, 0x50, 0x70, 0x12, 0x6f, 0x16, 0x0d, 0x00, 0x00,
}
